DT = 'test_diagram_tools'
SD = 'test_stacked_diagram'
BREAKS = [
 ('F1 log axis leaves 0 out', 'diagrams/diagram.cpp', 'if (xLog && x <= 0.0) continue;', ';', DT, ['huntMarkerOnALogAxisFromZero']),
 ('F1 log axis leaves 0 out (stacked)', 'diagrams/diagram.cpp', 'if (xLog && x <= 0.0) continue;', ';', SD, ['aLogAxisFromZero']),
 ('F1 marker on a graph not drawn', 'diagrams/marker.cpp', 'if (pGraph->isEmpty() || pGraph->cPointsY == nullptr) {', 'if (pGraph->isEmpty()) {', SD, ['aLogAxisFromZero']),
 ('F1 add_marker refuses a trace not drawn', 'qucscontrol_results.cpp', 'if (g->cPointsY == nullptr) return errorResult(tr("%1 is not drawn', 'if (false) return errorResult(tr("%1 is not drawn', DT, ['huntMarkerOnALogAxisFromZero']),
 ('F1 note: left off the log axis', 'qucscontrol_results.cpp', 'else if (const int off = d->leftOffLogAxis(g); off > 0)', 'else if (const int off = 0; off > 0)', DT, ['huntMarkerOnALogAxisFromZero']),
 ('F2 a segment of fewer than 8 samples', 'diagrams/spectrogramdiagram.cpp', 'if (length < 8 * interval) {', 'if (false) {', DT, ['huntASpectrogramsShortSegment']),
 ('F2 the columns over the whole run', 'diagrams/spectrogramdiagram.cpp', '(t.last() - t.first() - length) / (kMostColumns - 1)});', '0.0});', DT, ['huntASpectrogramsShortSegment']),
 ('F3 coordinates bounded', 'ltspiceimport.cpp', 'if (!ok || v < -kFarthest || v > kFarthest) return std::nullopt;', 'if (!ok) return std::nullopt;', DT, ['huntLtspiceImport']),
 ('A1 parts with an underscore', 'diagrams/tornadodiagram.cpp', '        if (!hasParameters) continue;', '        if (!hasParameters || n.contains(QLatin1Char(\'_\'))) continue;', DT, ['huntTornadoParts']),
 ('A1 ac.v(...) taken off', 'diagrams/tornadodiagram.cpp', 'if (const QRegularExpressionMatch m = wrapped.match(n); m.hasMatch()) n = m.captured(1);', ';', DT, ['huntTornadoParts']),
 ('A2 a limit goes with its pane', 'diagrams/stackeddiagram.cpp', 'if (l.pane >= n) l.pane = n - 1;', ';', SD, ['aLimitGoesWithItsPane']),
 ('A2 a limit past the panes read as the last', 'diagrams/stackeddiagram.cpp', 'const int pane = std::clamp(limit.pane, 0, paneCount() - 1);', 'if (limit.pane >= paneCount()) return nullptr; const int pane = limit.pane;', SD, ['aLimitGoesWithItsPane']),
 ('A2 unchecked: no pass', 'qucscontrol_results.cpp', 'QJsonObject verdict{{QStringLiteral("pass"), beyond.isEmpty() && unchecked.isEmpty()}};', 'QJsonObject verdict{{QStringLiteral("pass"), beyond.isEmpty()}};', DT, ['huntLimits']),
 ('A2 unchecked: check_schematic', 'erc.cpp', 'for (int li : qucs_s::limits::unchecked(d))', 'for (int li : QList<int>())', DT, ['huntLimits']),
 ('A3 f0 between the bins', 'spectrum.cpp', 'const double f1 = between(k1);', 'const double f1 = k1;', DT, ['huntSpectrumHarmonics']),
 ('A3 a harmonic a peak at its multiple', 'spectrum.cpp', '&& std::abs(between(i) - centre) <= 0.75 && s.amplitude.at(i) > 3.16 * floor', '', DT, ['huntSpectrumHarmonics']),
 ('A4 the width at 1e-12 the bathtub\'s', 'eyeanalysis.cpp', 'if (b.ok()) r.eyes[i].widthBer12 =', 'if (false) r.eyes[i].widthBer12 =', 'test_prbs_eye', ['theUnitIntervalIsToldFromTheCrossings']),
 ('A5 pin 2 the negative', 'probe.cpp', 'if (k == 2) return QLatin1Char(\'-\') + branch;', 'if (k == 2) return branch;', DT, ['huntProbedCurrents']),
 ('A6 relative_to before the marker is placed', 'qucscontrol_results.cpp', '    if (relative) placed->setReference(reference);', '    if (relative) setRelative(placed, d, args.value(QLatin1String("relative_to")), &error);', DT, ['huntMarkers']),
 ('B1 per kind prefixes', 'extsimkernels/abstractspicekernel.cpp', 'if ( a_needsPrefix || isCustom || a_prefixedSims.contains(dataset_prefix) )', 'if ( a_needsPrefix || isCustom || !a_prefixedSims.isEmpty() )', DT, ['huntPrefixedNames']),
 ('B1 a prefixed name found (text)', 'diagrams/diagram.cpp', 'if (count == 1 && (pFile = findVariable(found))) Variable = found;', ';', DT, ['huntPrefixedNames']),
 ('B1 a prefixed name found (binary)', 'diagrams/diagram.cpp', 'if (count == 1) at = data.find(found, true);', ';', 'test_binary_dataset', ['aGraphReadsBinaryAsItReadsText']),
 ('B1 a prefixed name found (get_dataset)', 'dataset.cpp', 'if (names.size() == 1) return names;\n    }\n    if (spice && analysisOf(w).isEmpty()) {', 'names.clear();\n    }\n    if (spice && analysisOf(w).isEmpty()) {', DT, ['huntPrefixedNames']),
 ('B2 a deleted reference forgotten', 'qucscontrol_results.cpp', '    d->forgetMarker(m);\n', '', DT, ['huntMarkers']),
 ('B3 probe1, not net1', 'probe.cpp', 'const QString name = QStringLiteral("probe%1").arg(i);', 'const QString name = QStringLiteral("net%1").arg(i);', DT, ['probingAnUnnamedNet']),
 ('B4 circles outside the sweep', 'diagrams/smithdiagram.cpp', 'if (circleFrequency < *lo - tolerance || circleFrequency > *hi + tolerance) {', 'if (false) {', DT, ['huntTheRest']),
 ('B5 add_diagram\'s run', 'qucscontrol_results.cpp', 'const bool fromRun = t.contains(QLatin1String("run"));', 'const bool fromRun = false;', DT, ['huntTheRest']),
 ('B6 a shown trace has data', 'probe.cpp', 'if (r.already && r.graph != nullptr && !r.graph->isEmpty()) r.hasData = true;', ';', DT, ['huntPrefixedNames', 'crossProbing']),
 ('B7 domain notes', 'qucscontrol_results.cpp', '    notes << domainNotes(d);\n    return notes;', '    return notes;', DT, ['huntASpectrogramsShortSegment']),
 ('B7 a spectrogram of an AC run', 'diagrams/spectrogramdiagram.cpp', 'if (xs != nullptr && xs->Var.contains(QLatin1String("freq"), Qt::CaseInsensitive)) {', 'if (false) {', DT, ['huntASpectrogramsShortSegment']),
 ('B8 rails a label can name', 'erc.cpp', '|posrail|avdd|dvdd|p\\\\d+v\\\\d*)$").arg(suffix)', '|posrail|avdd|dvdd)$").arg(suffix)', DT, ['huntTheRest']),
 ('B8 VIN no rail', 'erc.cpp', 'v(bat|sup|supply|bus)\\\\d*)$"', 'v(bat|in|sup|supply|bus|ref)\\\\d*)$"', DT, ['huntTheRest']),
 ('B8 ground names', 'erc.cpp', 'if (groundName.match(name).hasMatch()) grounds.insert(it.key());', ';', DT, ['huntTheRest']),
 ('B9 a marker\'s x whole', 'diagrams/marker.cpp', "s += QString::number(i, 'g', QLocale::FloatingPointShortest)+\"/\";", 's += QString::number(i)+"/";', DT, ['huntMarkers']),
 ('B10 a marker reads its own x\'s traces', 'diagrams/stackeddiagram.cpp', 'if (!over.isEmpty() && g->axis(0)->Var != over) continue;', ';', SD, ['aMarkerReadsEveryPane']),
 ('B11 the last point passed over drawn', 'diagrams/graph.cpp', '    if (skipped) {\n      lines.append(QLineF(segment_start, last_skipped));', '    if (false) {\n      lines.append(QLineF(segment_start, last_skipped));', SD, ['aSquaresEdgeIsWhereItIs']),
 ('B11 thinned again for a larger scale', 'diagrams/graph.cpp', '    || scaleNow > 1.5 * linesScale) {', '    ) {', SD, ['aSquaresEdgeIsWhereItIs']),
 ('B12 the emitter computed', 'probe.cpp', 'case \'q\': currents = {"ic", "ib", "-", "is"}; break;', 'case \'q\': currents = {"ic", "ib", "ie", "is"}; break;', DT, ['huntProbedCurrents']),
 ('B13 Qucsator\'s netlister', 'probe.cpp', 'if (QucsSettings.DefaultSimulator == spicecompat::simQucsator) {\n        // Qucsator\'s own netlister', 'if (false) {\n        // Qucsator\'s own netlister', DT, ['huntProbedCurrents']),
 ('B14 .step a Parameter Sweep', 'qucscontrol_design.cpp', 'if (lower.startsWith(QLatin1String(".step "))) {', 'if (false) {', DT, ['huntLtspiceImport']),
 ('B14 .meas said', 'ltspiceimport.cpp', 'if (word == QLatin1String(".meas") || word == QLatin1String(".measure"))', 'if (false)', DT, ['huntLtspiceImport']),
 ('B15 ratings left out', 'ltspiceimport.cpp', 'else if (listed ? !known.contains(key) : anyParasitic.match(key).hasMatch()) dropped << m.captured(0);', 'else if (!listed && anyParasitic.match(key).hasMatch()) dropped << m.captured(0);', DT, ['huntLtspiceImport']),
 ('B15 parasitics made parts', 'ltspiceimport.cpp', 'if (drawn.contains(key)) parasitics << std::pair{key, m.captured(2)};', 'if (drawn.contains(key)) dropped << m.captured(0);', DT, ['huntLtspiceImport']),
 ('B16 no grid over many turns', 'diagrams/nicholsdiagram.cpp', 'if (!grid || turnsInView() > MostTurns) return;', 'if (!grid) return;', DT, ['huntTheRest']),
 ('N1 a list of names', 'qucscontrol_results.cpp', 'if (what.isArray() && !whats.isEmpty() && std::all_of', 'if (false && std::all_of', DT, ['huntProbedCurrents']),
 ('N2 a spectrum from past the end', 'qucscontrol_results.cpp', 'if (g->cPointsY == nullptr || xs == nullptr || xs->count < 1) continue;\n                    const double end', 'continue;\n                    const double end', DT, ['huntSpectrumHarmonics']),
 ('N3 at outside said', 'diagrams/tornadodiagram.cpp', '                m_outside = true;\n', '', DT, ['huntTornadoParts']),
 ('N17 at between the samples', 'diagrams/tornadodiagram.cpp', 'b.value = valueOf(i - 1) + f * (valueOf(i) - valueOf(i - 1));', 'b.value = valueOf(f < 0.5 ? i - 1 : i);', DT, ['huntTornadoParts']),
 ('N4 the symbols cut said', 'diagrams/constellationdiagram.cpp', 'if (pair.points.size() >= kMostPoints && reached + period <= end)', 'if (false)', DT, ['huntTheRest']),
 ('N5 a bus named ""', 'qucscontrol_paintings.cpp', 'if (!get("name").isString() || !BusPainting::membersOf(name, &members)) {', 'if (!get("name").isString() || (!name.isEmpty() && !BusPainting::membersOf(name, &members))) {', DT, ['huntBusesAndDialogValues']),
 ('N6 a limit at one x', 'qucscontrol_results.cpp', 'if (l.points.first().x() == l.points.last().x()) {', 'if (false) {', DT, ['huntLimits']),
 ('N7 a limit that does not read', 'diagrams/diagram.cpp', 'if (qucs_s::limits::Limit::load(s, &limit)) limits.append(limit);', 'if (!qucs_s::limits::Limit::load(s, &limit)) return false; limits.append(limit);', DT, ['huntLimits']),
 ('N8 SpiceOrder said', 'ltspiceimport.cpp', 'if (!ok || order < 1 || orders.contains(order)) {', 'if (false) {', DT, ['huntLtspiceImport']),
 ('N9 box plot at not used', 'qucscontrol_results.cpp', 'if (std::isfinite(d->at) && k < d->Graphs.size() && d->Graphs.at(k)->countY == 1)', 'if (false)', DT, ['huntTheRest']),
 ('N10 iso-lines beyond the data', 'qucscontrol_results.cpp', 'if (lo >= 0 && (v < g.v.at(lo) || v > g.v.at(hi))) {', 'if (false) {', DT, ['huntTheRest']),
 ('N11 a prefix divides', 'valuereading.cpp', 'r.value = factor > 0 && factor < 1.0 ? n / std::round(1.0 / factor) : n * factor;', 'r.value = n * factor;', DT, ['huntBusesAndDialogValues']),
 ('N12 the marker\'s precision', 'diagrams/stackeddiagram.cpp', ': marker != nullptr ? marker->numberText(value) : numberText(value));', ': numberText(value));', SD, ['aMarkerReadsEveryPane']),
 ('N13 relative_to with none', 'qucscontrol_results.cpp', '    if (others < 1) {', '    if (false) {', DT, ['huntMarkers']),
 ('N14 UTF-16 big-endian', 'ltspiceimport.cpp', '    if (bomBE || nullsBE) {', '    if (false) {', DT, ['huntLtspiceImport']),
 ('N14 CR line ends', 'ltspiceimport.cpp', "return text.replace(QLatin1Char('\\r'), QLatin1Char('\\n'));", "return text.remove(QLatin1Char('\\r'));", DT, ['huntLtspiceImport']),
 ('N14 lines not read said', 'ltspiceimport.cpp', '    if (!unread.isEmpty())\n', '    if (false)\n', DT, ['huntLtspiceImport']),
 ('N15 a bus of no length', 'paintings/buspainting.cpp', 'if (m_started && x1 == x2 && y1 == y2) return false;', ';', DT, ['huntBusesAndDialogValues']),
 ('N16 one warning a limit', 'erc.cpp', 'const QString stretches = list.size() > 1 ?', 'const QString stretches = false ?', DT, ['huntLimits']),
 ('N18 models defined nowhere', 'ltspiceimport.cpp', '    if (!undefined.isEmpty())\n', '    if (false)\n', DT, ['huntLtspiceImport']),
 ('N19 flags renamed', 'ltspiceimport.cpp', "    if (s.startsWith(QLatin1Char('+'))) s = QLatin1Char('P') + s.mid(1);", "    if (false) s = QLatin1Char('P') + s.mid(1);", DT, ['huntLtspiceImport']),
 ('N20 a zero\'s minimum phase', 'qucscontrol_results.cpp', 'if (PoleZeroDiagram::isZero(g)) ro.insert(QStringLiteral("minimum phase"), r.re < 0);', 'if (false) ro.insert(QStringLiteral("minimum phase"), r.re < 0);', DT, ['huntTheRest']),
 ('N21 the offset past the run said', 'diagrams/constellationdiagram.cpp', 'if (std::isfinite(period) && period > 0 && std::isfinite(offset) && offset > end) {', 'if (false) {', DT, ['huntTheRest']),
 ('N22 values at the marker kept', 'schematic_file.cpp', '  if (a_cursorValues) {\n    int number = 0, k = 0;', '  if (false) {\n    int number = 0, k = 0;', DT, ['huntTheRest']),
 ('N23 Δ in the complex plane', 'qucscontrol_results.cpp', '            delta.insert(QStringLiteral("magnitude"), number(', '            if (false) delta.insert(QStringLiteral("magnitude"), number(', DT, ['huntMarkers']),

 ('B6 a dataset named before the variable (inData)', 'probe.cpp', 'const QString bare = kept.isEmpty() ? name : name.mid(kept.size() + 1);', 'const QString bare = name;', DT, ['huntPrefixedNames']),
 ('B1 a trace keeps its spelling', 'qucscontrol_results.cpp', '                return named(bare);\n            return named(n);', '                return named(n);\n            return named(n);', DT, ['huntPrefixedNames']),
 ('A5 a computed current as the name alone (get_dataset)', 'dataset.cpp', '[vViI]\\\\(([A-Za-z_][A-Za-z0-9_]*)', '[vV]\\\\(([A-Za-z_][A-Za-z0-9_]*)', DT, ['huntProbedCurrents']),
 ('A5 a computed current as the name alone (graphs)', 'diagrams/graph.cpp', 'if (const QRegularExpressionMatch m = current.match(var); m.hasMatch()) return m.captured(1) + m.captured(2);', ';', DT, ['huntProbedCurrents']),

 ('N13 NRZ read as PAM4 said', 'eyeanalysis.cpp', '        else if (gap2 > 1.6 * std::max(gap1, gap3))', '        else if (false)', DT, ['huntTheRest']),
]
