# import_data and the trace rules at their edges.
import os, sys, json, shutil
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from mcp import Server, HERE
ws = HERE + '/ws_import'; shutil.rmtree(ws, ignore_errors=True); os.makedirs(ws)
s = Server(ws)
def c(tool, args):
    try: return s.call(tool, args)
    except RuntimeError as e: return 'ERROR ' + str(e)[:400]
def show(label, r): print('==', label, '\n  ', (json.dumps(r) if not isinstance(r, str) else r)[:700])
open(ws + '/m.csv', 'w').write('t,a,b\n0,1,2\n1,3,4\n2,5,6\n')
c('new_document', {}); c('save_document', {'as': 'p.sch'})
show('name ..', c('import_data', {'file': 'm.csv', 'name': '..'}))
show('name with dot', c('import_data', {'file': 'm.csv', 'name': 'a.b'}))
show('name digits', c('import_data', {'file': 'm.csv', 'name': '123'}))
show('name "p_" ok', c('import_data', {'file': 'm.csv', 'name': 'p_'}))
show('x empty string', c('import_data', {'file': 'm.csv', 'x': ''}))
show('x "row" when a column is row', None)
open(ws + '/r.csv', 'w').write('row,v\n5,1\n6,2\n')
show('  ->', c('import_data', {'file': 'r.csv', 'x': 'row'}))
show('file = a folder', c('import_data', {'file': '.'}))
show('file = the schematic', c('import_data', {'file': 'p.sch'}))
show('file = an imported dataset', c('import_data', {'file': 'm.dat'}))
show('file = a dataset of ngspice beside', None)
open(ws + '/p.dat.ngspice', 'w').write('<Qucs Dataset 26.1.4>\n<indep time 2>\n0\n1\n</indep>\n<dep tran.v(out) time>\n1\n2\n</dep>\n')
show('  ->', c('import_data', {'file': 'p.dat.ngspice'}))
show('empty csv', (open(ws + '/e.csv', 'w').write(''), c('import_data', {'file': 'e.csv'}))[1])
show('header only', (open(ws + '/h.csv', 'w').write('a,b\n'), c('import_data', {'file': 'h.csv'}))[1])
show('one column', (open(ws + '/o.csv', 'w').write('a\n1\n2\n'), c('import_data', {'file': 'o.csv'}))[1])
show('names with colon and slash', (open(ws + '/n.csv', 'w').write('t,v:1,w/2,x y\n0,1,2,3\n1,2,3,4\n'), c('import_data', {'file': 'n.csv'}))[1])
show('trace of v:1', c('add_diagram', {'traces': ['n:v_1']}))
show('reload with no name nor file', c('import_data', {'reload': True}))
show('remove by file', c('import_data', {'file': 'o.csv', 'remove': True}))
show('reload after its source is gone', (os.remove(ws + '/h.csv'), c('import_data', {'name': 'h', 'reload': True}))[1])
show('list_documents', c('list_documents', {'kind': 'dataset'}))
s.close()
