"""p16: the Libraries panel after import_library (a SPICE library and a Qucs-S one, into user_lib and into the project)."""
import os, re, json, mcp, lib
s = mcp.Server('p16')
d = lib.project(s, 'pn', {'div.sch': lib.divider('1k', '3k')})
src = s.root + '/src'
os.makedirs(src)
open(src + '/vend.lib', 'w').write('* vendor\n.subckt VDIV 1 2\nR1 1 2 1k\nR2 2 0 1k\n.ends VDIV\n.subckt VTWO 1 2\nR1 1 2 1k\n.ends VTWO\n')
s.call('create_library', {'name': 'QL', 'destination': 'project'})
os.rename(d + '/QL.lib', src + '/QL.lib')
s.call('import_library', {'path': src + '/vend.lib'})
s.call('import_library', {'path': src + '/QL.lib'})
s.call('import_library', {'path': src + '/vend.lib', 'destination': 'project'})
areas = s.call('get_ui', {})
print('areas:', json.dumps(areas)[:400])
ui = s.call('get_ui', {'area': 'dock:Main Dock/Libraries'})
text = json.dumps(ui)
print('panel:', text[:300])
tree = next(c for c in ui['controls'] if c.get('kind') == 'tree')
rows = [r[0] if isinstance(r, list) else r for r in tree['rows']]
heads = [i for i, r in enumerate(rows) if re.search(r'(?i)librar|project', str(r))]
print('section rows:', [rows[i] for i in heads])
print('after System Libraries:', [r for r in rows if re.search(r'(?i)vend|^QL|VDIV|VTWO|^div', str(r))])
print('last 12 rows:', rows[-12:], 'count', len(rows), {k: v for k, v in tree.items() if k != 'rows'})
ui2 = s.call('set_ui', {'area': 'dock:Main Dock/Libraries', 'set': {'c1': 'VDIV'}})
ui = s.call('get_ui', {'area': 'dock:Main Dock/Libraries'})
tree = next(c for c in ui['controls'] if c.get('kind') == 'tree')
print('filtered VDIV:', tree['rows'][:20])
ui2 = s.call('set_ui', {'area': 'dock:Main Dock/Libraries', 'set': {'c1': 'div'}})
tree = next(c for c in s.call('get_ui', {'area': 'dock:Main Dock/Libraries'})['controls'] if c.get('kind') == 'tree')
print('filtered div:', tree['rows'][:20])
r = s.call('set_ui', {'area': 'dock:Main Dock/Libraries', 'set': {'c1': ''}})
r = s.call('set_ui', {'area': 'dock:Main Dock/Libraries', 'set': {'c3': 'System Libraries'}, 'action': 'collapse'})
print('collapse:', str(r)[:200])
tree = next(c for c in s.call('get_ui', {'area': 'dock:Main Dock/Libraries'})['controls'] if c.get('kind') == 'tree')
print('rows after collapsing System Libraries:', tree['rows'][:40])
s.close()
